# Generated by Django 3.2 on 2022-03-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docuware',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Item')),
                ('Document_ID', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('Payee_Name', models.CharField(blank=True, max_length=250, null=True)),
                ('Payment_Requisition_Number', models.CharField(blank=True, max_length=250, null=True)),
                ('FMS_Process', models.CharField(blank=True, max_length=50, null=True)),
                ('TQ_Status', models.CharField(blank=True, max_length=50, null=True)),
                ('Amount', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
