# Generated by Django 3.2 on 2022-03-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tqapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docuware',
            name='Amount',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='docuware',
            name='Document_ID',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
